"""Tests for the pptx-arch-style linter.

Fixtures live under ``fixtures/`` and are regenerated by ``gen_fixtures.js``
(committed alongside). Tests load the linter as a module so we can call
``lint()``/``exit_code()`` directly without invoking the CLI.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
SCRIPT = HERE.parent / "lint.py"
FIXTURES = HERE / "fixtures"
RULES = HERE.parent.parent / "references" / "rules.yaml"


def _load_module():
    spec = importlib.util.spec_from_file_location("pptx_arch_lint", SCRIPT)
    assert spec and spec.loader, f"cannot load {SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    # Register in sys.modules before exec so @dataclass can resolve cls.__module__.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


lint_mod = _load_module()


@pytest.fixture(scope="module")
def rules():
    return lint_mod.load_rules(RULES)


def _violation_ids(report):
    return {v.rule_id for v in report.violations}


def test_golden_passes(rules):
    report = lint_mod.lint(FIXTURES / "golden.pptx", rules)
    assert report.violations == [], f"unexpected violations: {report.violations}"
    assert report.untagged_slides == []
    assert lint_mod.exit_code(report) == 0


VIOLATORS = [
    ("content-must-have-page-badge.pptx", "content-must-have-page-badge"),
    ("content-must-have-red-line.pptx", "content-must-have-red-line"),
    ("title-no-page-badge.pptx", "title-no-page-badge"),
    ("section-no-red-line.pptx", "section-no-red-line"),
    ("red-accent-line-coords.pptx", "red-accent-line-coords"),
    ("brand-red-must-use-F12D16.pptx", "brand-red-must-use-F12D16"),
    ("red-highlight-marker-border.pptx", "red-highlight-marker-border"),
    (
        "text-runs-use-approved-font-and-size.pptx",
        "text-runs-use-approved-font-and-size",
    ),
    ("section-text-centered.pptx", "section-text-centered"),
    ("background-effectLst-override.pptx", "background-effectLst-override"),
]


@pytest.mark.parametrize("fixture,expected_rule", VIOLATORS)
def test_violator_reports_expected_rule(rules, fixture, expected_rule):
    report = lint_mod.lint(FIXTURES / "violators" / fixture, rules)
    assert expected_rule in _violation_ids(report), (
        f"expected rule '{expected_rule}' to fail on {fixture}; "
        f"got {_violation_ids(report)}"
    )
    assert lint_mod.exit_code(report) == 1


def test_untagged_slide_flags_classification_error(rules):
    report = lint_mod.lint(FIXTURES / "violators" / "untagged-slide.pptx", rules)
    assert report.untagged_slides, "untagged slide should be detected"
    assert lint_mod.exit_code(report) == 1


def test_edge_within_tolerance_passes(rules):
    report = lint_mod.lint(FIXTURES / "edge" / "red-line-within-tolerance.pptx", rules)
    assert "red-accent-line-coords" not in _violation_ids(report), (
        f"0.003in drift should pass under 0.005 tolerance; got {report.violations}"
    )
    assert lint_mod.exit_code(report) == 0


def test_edge_outside_tolerance_fails(rules):
    report = lint_mod.lint(
        FIXTURES / "edge" / "red-line-outside-tolerance.pptx", rules
    )
    assert "red-accent-line-coords" in _violation_ids(report), (
        f"0.010in drift should fail past 0.005 tolerance; got {report.violations}"
    )
    assert lint_mod.exit_code(report) == 1


def test_every_rule_type_has_at_least_one_rule(rules):
    """AC#2: rules.yaml covers all 8 rule types with at least one instance each."""
    required = {
        "mandatory_element",
        "forbidden_element",
        "shape_coordinates",
        "fill_color",
        "border_spec",
        "font_spec",
        "text_alignment",
        "effect_override",
    }
    present = {r["type"] for r in rules}
    assert required.issubset(present), (
        f"missing rule types: {required - present}; present: {present}"
    )


def test_every_rule_has_spec_ref(rules):
    """AC#2: every rule has spec_ref field."""
    missing = [r["id"] for r in rules if not r.get("spec_ref")]
    assert not missing, f"rules missing spec_ref: {missing}"


def test_main_cli_exit_codes(rules, capsys):
    """End-to-end smoke check via main()."""
    code = lint_mod.main(
        [str(FIXTURES / "golden.pptx"), "--rules", str(RULES)]
    )
    assert code == 0

    code = lint_mod.main(
        [
            str(FIXTURES / "violators" / "content-must-have-page-badge.pptx"),
            "--rules",
            str(RULES),
        ]
    )
    assert code == 1
