"""Tests for the pptx-arch-style linter.

Fixtures live under ``fixtures/`` and are regenerated by ``gen_fixtures.js``
(committed alongside). Tests load the linter as a module so we can call
``lint()``/``exit_code()`` directly without invoking the CLI.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
SCRIPT = HERE.parent / "lint.py"
FIXTURES = HERE / "fixtures"
RULES = HERE.parent.parent / "references" / "rules.yaml"


def _load_module():
    spec = importlib.util.spec_from_file_location("pptx_arch_lint", SCRIPT)
    assert spec and spec.loader, f"cannot load {SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    # Register in sys.modules before exec so @dataclass can resolve cls.__module__.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


lint_mod = _load_module()


@pytest.fixture(scope="module")
def rules():
    return lint_mod.load_rules(RULES)


def _violation_ids(report):
    return {v.rule_id for v in report.violations}


def test_golden_passes(rules):
    report = lint_mod.lint(FIXTURES / "golden.pptx", rules)
    assert report.violations == [], f"unexpected violations: {report.violations}"
    assert report.untagged_slides == []
    assert lint_mod.exit_code(report) == 0


VIOLATORS = [
    ("content-must-have-page-badge.pptx", "content-must-have-page-badge"),
    ("content-must-have-red-line.pptx", "content-must-have-red-line"),
    ("title-no-page-badge.pptx", "title-no-page-badge"),
    ("section-no-red-line.pptx", "section-no-red-line"),
    ("red-accent-line-coords.pptx", "red-accent-line-coords"),
    ("brand-red-must-use-F12D16.pptx", "brand-red-must-use-F12D16"),
    ("red-highlight-marker-border.pptx", "red-highlight-marker-border"),
    (
        "text-runs-use-approved-font-and-size.pptx",
        "text-runs-use-approved-font-and-size",
    ),
    ("section-text-centered.pptx", "section-text-centered"),
    ("background-effectLst-override.pptx", "background-effectLst-override"),
]


@pytest.mark.parametrize("fixture,expected_rule", VIOLATORS)
def test_violator_reports_expected_rule(rules, fixture, expected_rule):
    report = lint_mod.lint(FIXTURES / "violators" / fixture, rules)
    assert expected_rule in _violation_ids(report), (
        f"expected rule '{expected_rule}' to fail on {fixture}; "
        f"got {_violation_ids(report)}"
    )
    assert lint_mod.exit_code(report) == 1


def test_off_palette_fill_warns(rules):
    """AC#2: off-palette shape fill emits the palette-fill-warning rule at
    severity warning; lint.py exits 2 (warnings only, no errors)."""
    report = lint_mod.lint(FIXTURES / "violators" / "palette-fill-warning.pptx", rules)
    assert "palette-fill-warning" in _violation_ids(report)
    palette_violations = [v for v in report.violations if v.rule_id == "palette-fill-warning"]
    assert all(v.severity == "warning" for v in palette_violations)
    assert lint_mod.exit_code(report) == 2


def test_untagged_slide_flags_classification_error(rules):
    report = lint_mod.lint(FIXTURES / "violators" / "untagged-slide.pptx", rules)
    assert report.untagged_slides, "untagged slide should be detected"
    assert lint_mod.exit_code(report) == 1


def test_decision_tree_diagonal_connector_warns(rules):
    """AC#3/AC#4 (TASK-25): a LINE shape with both w>0.05in AND h>0.05in is a
    diagonal connector and must fire decision-tree-connector-orthogonal at
    severity warning; lint.py exits 2 (warnings only, no errors)."""
    report = lint_mod.lint(
        FIXTURES / "violators" / "decision-tree-connector-orthogonal.pptx", rules
    )
    assert "decision-tree-connector-orthogonal" in _violation_ids(report)
    diag_violations = [
        v for v in report.violations if v.rule_id == "decision-tree-connector-orthogonal"
    ]
    assert all(v.severity == "warning" for v in diag_violations)
    assert lint_mod.exit_code(report) == 2


def test_decision_tree_orthogonal_clean_passes(rules):
    """AC#4 (TASK-25): a canonical decision-tree built per the SKILL.md recipe
    (vertical + horizontal LINE segments) lints clean — exit 0."""
    report = lint_mod.lint(
        FIXTURES / "edge" / "decision-tree-orthogonal-clean.pptx", rules
    )
    assert "decision-tree-connector-orthogonal" not in _violation_ids(report), (
        f"orthogonal LINE shapes (w=0 or h=0) should not fire the rule; "
        f"got {report.violations}"
    )
    # Both LINEs in the clean fixture sit at y=1.5 and y=2.5, above the
    # decision-tree-connector-arrowhead-missing rule's y_min: 3.6 terminal-band
    # filter — so that rule does NOT fire here. The fixture's purpose is to
    # smoke-test pure orthogonality; the arrowhead-missing rule (TASK-28) has
    # its own dedicated fixture pair (decision-tree-arrowhead-{missing,present}).
    assert lint_mod.exit_code(report) == 0


def test_decision_tree_arrowhead_missing_warns(rules):
    """AC#5 (TASK-28): a gray (#595959) LINE shape without beginArrowType /
    endArrowType fires decision-tree-connector-arrowhead-missing at severity
    warning; lint.py exits 2 (warnings only, no errors)."""
    report = lint_mod.lint(
        FIXTURES / "violators" / "decision-tree-connector-arrowhead-missing.pptx",
        rules,
    )
    assert "decision-tree-connector-arrowhead-missing" in _violation_ids(report)
    arrow_violations = [
        v for v in report.violations
        if v.rule_id == "decision-tree-connector-arrowhead-missing"
    ]
    assert all(v.severity == "warning" for v in arrow_violations)
    assert lint_mod.exit_code(report) == 2


def test_decision_tree_arrowhead_present_passes(rules):
    """AC#5 (TASK-28): a gray LINE shape with endArrowType: 'triangle' does
    NOT trigger the arrowhead-missing rule and lints clean — exit 0."""
    report = lint_mod.lint(
        FIXTURES / "edge" / "decision-tree-arrowhead-present.pptx", rules
    )
    assert "decision-tree-connector-arrowhead-missing" not in _violation_ids(report), (
        f"a LINE with endArrowType: 'triangle' should not fire the rule; "
        f"got {report.violations}"
    )
    assert lint_mod.exit_code(report) == 0


def test_edge_within_tolerance_passes(rules):
    report = lint_mod.lint(FIXTURES / "edge" / "red-line-within-tolerance.pptx", rules)
    assert "red-accent-line-coords" not in _violation_ids(report), (
        f"0.003in drift should pass under 0.005 tolerance; got {report.violations}"
    )
    assert lint_mod.exit_code(report) == 0


def test_edge_outside_tolerance_fails(rules):
    report = lint_mod.lint(
        FIXTURES / "edge" / "red-line-outside-tolerance.pptx", rules
    )
    assert "red-accent-line-coords" in _violation_ids(report), (
        f"0.010in drift should fail past 0.005 tolerance; got {report.violations}"
    )
    assert lint_mod.exit_code(report) == 1


def test_every_rule_type_has_at_least_one_rule(rules):
    """AC#2: rules.yaml covers all 8 rule types with at least one instance each."""
    required = {
        "mandatory_element",
        "forbidden_element",
        "shape_coordinates",
        "fill_color",
        "border_spec",
        "font_spec",
        "text_alignment",
        "effect_override",
    }
    present = {r["type"] for r in rules}
    assert required.issubset(present), (
        f"missing rule types: {required - present}; present: {present}"
    )


def test_every_rule_has_spec_ref(rules):
    """AC#2: every rule has spec_ref field."""
    missing = [r["id"] for r in rules if not r.get("spec_ref")]
    assert not missing, f"rules missing spec_ref: {missing}"


def test_title_zone_smoke_test_v070_geometry(rules):
    """TASK-27 (v0.7.0 path c): a deck with 1-line AND 2-line titles built per
    the canonical recipe lints clean AND its geometry is internally
    consistent:

      * title text box bottom-y == red line top-y == 0.85 (top-anchored
        24pt text cannot drop below 0.85 because valign=top pins the first
        line baseline near y=0)
      * subtitle bottom-y (0.90 + 0.18 = 1.08) sits above content top y=1.10
        with a 0.02in gap — no overlap
      * red line at y=0.85 with h=0.042 ends at y=0.892, subtitle top y=0.90
        leaves an 0.008in gap below the red line — no overlap
    """
    from pptx import Presentation as _Pres

    fixture = FIXTURES / "edge" / "title-zone-smoke-test.pptx"
    report = lint_mod.lint(fixture, rules)
    assert report.violations == [], f"v0.7.0 smoke deck must lint clean; got {report.violations}"
    assert lint_mod.exit_code(report) == 0

    deck = _Pres(str(fixture))
    EMU = 914400

    def _is_title(shape):
        if not shape.has_text_frame:
            return False
        text = shape.text_frame.text
        lowered = text.lower()
        # Exclude subtitle (which also contains "title") and page-number badge.
        if "subtitle" in lowered:
            return False
        return "title" in lowered or "Рекомендация" in text

    for idx, slide in enumerate(deck.slides, start=1):
        shapes = list(slide.shapes)
        title_shapes = [s for s in shapes if _is_title(s)]
        red_lines = [
            s
            for s in shapes
            if (s.width or 0) / EMU >= 9.5 and (s.height or 0) / EMU <= 0.10
        ]
        assert red_lines, f"slide {idx}: red accent line not found"
        red = red_lines[0]
        red_y = (red.top or 0) / EMU
        red_h = (red.height or 0) / EMU
        assert abs(red_y - 0.85) < 0.005, (
            f"slide {idx}: red line y={red_y} (expected 0.85)"
        )
        assert title_shapes, f"slide {idx}: title shape not found"
        for t in title_shapes:
            top = (t.top or 0) / EMU
            h = (t.height or 0) / EMU
            bottom = top + h
            assert bottom <= red_y + 0.005, (
                f"slide {idx}: title shape bottom y={bottom} crosses red line y={red_y}"
            )

        subtitle_shapes = [
            s
            for s in shapes
            if s.has_text_frame
            and "subtitle" in s.text_frame.text.lower()
        ]
        assert subtitle_shapes, f"slide {idx}: subtitle shape not found"
        sub = subtitle_shapes[0]
        sub_top = (sub.top or 0) / EMU
        sub_h = (sub.height or 0) / EMU
        sub_bottom = sub_top + sub_h
        assert sub_top >= red_y + red_h - 0.005, (
            f"slide {idx}: subtitle top y={sub_top} overlaps red line bottom y={red_y + red_h}"
        )
        assert sub_bottom <= 1.10 + 0.005, (
            f"slide {idx}: subtitle bottom y={sub_bottom} crosses content top y=1.10"
        )


def test_main_cli_exit_codes(rules, capsys):
    """End-to-end smoke check via main()."""
    code = lint_mod.main(
        [str(FIXTURES / "golden.pptx"), "--rules", str(RULES)]
    )
    assert code == 0

    code = lint_mod.main(
        [
            str(FIXTURES / "violators" / "content-must-have-page-badge.pptx"),
            "--rules",
            str(RULES),
        ]
    )
    assert code == 1
