"""Tests for the pptx-compare structural comparison.

The fixtures under ``fixtures/`` are two one-slide decks regenerated by
``gen_fixtures.py``, identical apart from three planted discrepancies. Each
test asserts the parse finds exactly those and invents nothing else.

``compare_decks`` is imported as a plain module — putting its directory on
``sys.path`` is enough, because the scripts here are named with underscores.
The sibling pptx-arch-style tests need an ``importlib`` file loader instead,
because the scripts there are hyphenated and so cannot be imported by name.
That loader must not be copied into this tree.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent
FIXTURES = HERE / "fixtures"

if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import compare_decks  # noqa: E402

REF = FIXTURES / "ref.pptx"
GEN = FIXTURES / "gen.pptx"

# The 0.10in offset planted in gen.pptx, either side of which the coordinate
# discrepancy has to appear and disappear.
TOL_BELOW_OFFSET = compare_decks.DEFAULT_POS_TOL_EMU  # 0.04in
TOL_ABOVE_OFFSET = int(0.25 * compare_decks.EMU_PER_INCH)


def _lines(report) -> list[str]:
    return [line for slide in report.slides for line in slide.lines]


def test_fixtures_exist():
    assert REF.exists() and GEN.exists(), "run gen_fixtures.py to build the fixtures"


def test_deck_compared_with_itself_is_clean():
    report = compare_decks.compare_decks(REF, REF)
    assert report.ok
    assert report.diff_count == 0


def test_planted_discrepancies_are_all_found():
    report = compare_decks.compare_decks(REF, GEN, TOL_BELOW_OFFSET)
    assert not report.ok
    assert len(report.slides) == 1
    lines = _lines(report)
    assert len(lines) == 3, lines

    size, offset, unmatched = lines
    assert "size: ref=28.0 gen=24.0" in size
    assert "title" in size
    assert "x: ref=548640 gen=640080" in offset
    assert "body-box" in offset
    assert unmatched.startswith("only in gen:")
    assert "extra-note" in unmatched


def test_coordinate_delta_is_silenced_by_a_wider_tolerance():
    report = compare_decks.compare_decks(REF, GEN, TOL_ABOVE_OFFSET)
    lines = _lines(report)
    assert len(lines) == 2, lines
    assert not any("body-box" in line for line in lines)


def test_slide_count_mismatch_is_fatal(tmp_path):
    from pptx import Presentation

    short = tmp_path / "empty.pptx"
    Presentation().save(str(short))
    report = compare_decks.compare_decks(REF, short)
    assert report.fatal is not None
    assert "slide count differs" in report.fatal
    assert not report.ok


def test_matching_pairs_shapes_by_cost_not_by_index():
    """The extra gen shape must not shunt every later shape into a false diff."""
    ref_shapes = compare_decks.parse_deck(REF)[0]
    gen_shapes = compare_decks.parse_deck(GEN)[0]
    pairs = compare_decks.match_shapes(ref_shapes, gen_shapes)
    matched = {
        (a.name, b.name) for a, b in pairs if a is not None and b is not None
    }
    assert matched == {("title", "title"), ("body-box", "body-box")}
    assert [b.name for a, b in pairs if a is None] == ["extra-note"]


def test_cli_pos_tol_flag_is_exposed_in_inches():
    args = compare_decks.build_parser().parse_args([str(REF), str(GEN)])
    assert args.pos_tol == pytest.approx(
        compare_decks.DEFAULT_POS_TOL_EMU / compare_decks.EMU_PER_INCH
    )
    widened = compare_decks.build_parser().parse_args(
        [str(REF), str(GEN), "--pos-tol", "0.25"]
    )
    assert widened.pos_tol == pytest.approx(0.25)


def test_cli_outdir_has_no_default_beside_the_script():
    args = compare_decks.build_parser().parse_args([str(REF), str(GEN)])
    assert args.outdir is None


def test_exit_codes(capsys):
    assert compare_decks.main([str(REF), str(REF)]) == 0
    assert compare_decks.main([str(REF), str(GEN)]) == 1
    capsys.readouterr()
